pismeni-ispiti/zadaci/januar2019_resenje/MasterTeme/Components/SmeroviViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MasterTeme.Models;
using System.Linq;
using System.Collections.Generic;

namespace MasterTeme.Components{

    public class SmeroviViewComponent : ViewComponent {
        private ApplicationDbContext repozitorijum;

        public SmeroviViewComponent(ApplicationDbContext repo)
        {
            repozitorijum = repo;
        }

        public IViewComponentResult Invoke() =>
            View(repozitorijum.Studenti.Select(p => p.Smer).Distinct().OrderBy(p => p));
        
    }
}

pismeni-ispiti/zadaci/januar2019_resenje/MasterTeme/Controllers/UnosPodatakaController.cs
using Microsoft.AspNetCore.Mvc;
using MasterTeme.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using MasterTeme.ViewModels;

namespace MasterTeme.Controllers {

	public class UnosPodatakaController : Controller {
		private ApplicationDbContext repozitorijum;

		public UnosPodatakaController(ApplicationDbContext repo)
		{
			repozitorijum = repo;
		}

        public ViewResult UnosNastavnika()
        {
            return View();
        }

        [HttpPost]
        public ViewResult UnosNastavnika(Nastavnik nastavnik)
        {
            if (ModelState.IsValid)
            {
                repozitorijum.SacuvajNastavnika(nastavnik);
                TempData["message"] = $"{nastavnik.Ime} {nastavnik.Prezime} je sačuvan!";
                return View();
            }
            else
                return View();
        }

        public ViewResult UnosStudenta()
        {
            return View();
        }

        [HttpPost]
        public ViewResult UnosStudenta(Student student)
        {
            if (ModelState.IsValid)
            {
                if (repozitorijum.SacuvajStudenta(student))
                    TempData["message"] = $"{student.Ime} {student.Prezime} je sačuvan!";
                else
                    ModelState.AddModelError("", "Student sa datim indeksom vec postoji");
                return View();
            }
            else
                return View();
        }

        public ViewResult UnosMasterTeme()
        {
            return View(new MasterTemaViewModel{Nastavnici = repozitorijum.Nastavnici});
        }

        [HttpPost]
        public ViewResult UnosMasterTeme(MasterTemaViewModel masterViewTema)
        {
            if (ModelState.IsValid)
            {
                Student s1 = repozitorijum.Studenti.FirstOrDefault(p => p.Indeks == masterViewTema.Indeks);

                if (s1 == null)
                    ModelState.AddModelError("", "Master tema nije uspesno sacuvana, student ne postoji");
                else
                {

                    MasterTema masterTema = new MasterTema{
                        Naziv = masterViewTema.Naziv,
                        Student = s1,
                        Mentor =  repozitorijum.Nastavnici.FirstOrDefault(p => p.NastavnikId == masterViewTema.NastavnikId),
                        DatumNNV = masterViewTema.DatumNNV
                    };

                    List<KomisijaElement> komisija = new List<KomisijaElement>();
                    foreach(var nastavnikId in masterViewTema.KomisijaId)
                    {
                        komisija.Add(new KomisijaElement{
                            Nastavnik = repozitorijum.Nastavnici.FirstOrDefault(p => p.NastavnikId == nastavnikId)});
                    }
                    masterTema.Komisija = komisija.AsEnumerable();

                    if (repozitorijum.SacuvajMasterTemu(masterTema))
                        TempData["message"] = $"Tema {masterTema.Naziv} je sačuvana!";
                    else
                        ModelState.AddModelError("", "Master tema nije uspesno sacuvana");
                }
                return View(new MasterTemaViewModel{Nastavnici = repozitorijum.Nastavnici});
            }
            else
                return View(new MasterTemaViewModel{Nastavnici = repozitorijum.Nastavnici});
        }
    }
}

pismeni-ispiti/zadaci/januar2019_resenje/MasterTeme/Views/Shared/TemeIspis.cshtml
@model MasterTema

@{
    var i=0;
    var count = Model.Komisija.Count();
}

<div class="panel panel-success" style="width:80%;">
    <div class="panel-heading">
        <h3 class="panel-title">@Model.Naziv</h3>
    </div>
    <div class="panel-body">
        <h4><b>@Model.Student.Ime @Model.Student.Prezime</b>, @Model.Student.Indeks, <b>@Model.Student.Smer</b> smer</h4><br>
        <b>mentor:</b> @Model.Mentor.Ime @Model.Mentor.Prezime <br>
        <b>članovi komisije:</b>
        @foreach (var p in Model.Komisija)
        {
            if(++i==count)
            {
                <span>@p.Nastavnik.Ime</span>
                <span>@p.Nastavnik.Prezime</span>
            }
            else
            {
               <span>@p.Nastavnik.Ime</span>
               <span>@p.Nastavnik.Prezime,</span> 
            }
            
        }
        <br>
        <b>datum odluke NNV:</b> @Model.DatumNNV.ToString("d")
    </div>
</div>

pismeni-ispiti/zadaci/januar2019_resenje/MasterTeme/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Master Teme</title>
	    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">

    <link rel="stylesheet" asp-href-include="/lib/bootstrap/dist/**/*.min.css"
                           asp-href-exclude="**/*-reboot*,**/*-grid*" />
</head>
<body>
    <nav class="navbar navbar-inverse">
	    <a class="navbar-brand" href="/">MASTER TEME</a>

        <div class="text-right">
        <a class="btn btn-info" asp-controller="UnosPodataka" asp-action="UnosStudenta">Uneti Novog Studenta</a>
        <a class="btn btn-info" asp-controller="UnosPodataka" asp-action="UnosNastavnika">Uneti Novog Nastavnika</a>
        <a class="btn btn-info" asp-controller="UnosPodataka" asp-action="UnosMasterTeme">Uneti Novu Master Temu</a>
        </div>  
	</nav>
   
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-10">
                @RenderBody()
            </div>
        </div>
    </div>
  
</body>
</html>

pismeni-ispiti/zadaci/januar2019_resenje/MasterTeme/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Master Teme</title>
	    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">

    <link rel="stylesheet" asp-href-include="/lib/bootstrap/dist/**/*.min.css"
                           asp-href-exclude="**/*-reboot*,**/*-grid*" />
</head>
<body>
    <nav class="navbar navbar-inverse">
	    <a class="navbar-brand" href="#">MASTER TEME</a>

    <div class="text-right">
    <a class="btn btn-info" asp-controller="UnosPodataka" asp-action="UnosStudenta">Uneti Novog Studenta</a>
    <a class="btn btn-info" asp-controller="UnosPodataka" asp-action="UnosNastavnika">Uneti Novog Nastavnika</a>
    <a class="btn btn-info" asp-controller="UnosPodataka" asp-action="UnosMasterTeme">Uneti Novu Master Temu</a>
    </div>  

    </nav>      
   
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                @await Component.InvokeAsync("Smerovi")
            </div>
            <div class="col-md-10">
                @RenderBody()
            </div>
        </div>
    </div>
  
</body>
</html>