pismeni-ispiti/zadaci/januar2019_resenje/MasterTeme/Controllers/MasterTemeController.cs
using Microsoft.AspNetCore.Mvc;
using MasterTeme.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace MasterTeme.Controllers {

	public class MasterTemeController : Controller {
		private ApplicationDbContext repozitorijum;

		public MasterTemeController(ApplicationDbContext repo)
		{
			repozitorijum = repo;
		}
		
		public ViewResult Spisak(string smer="") 
		{
			List<MasterTema> rezultat = repozitorijum.MasterTeme.Include(p => p.Mentor).Include(p => p.Student).
					Include(p => p.Komisija).ThenInclude(p => p.Nastavnik).OrderBy(p => p.DatumNNV).ToList();

			if (smer == null)
			{
				return View(rezultat);
			}
			else
			{
				return View(rezultat.Where(p => p.Student.Smer == smer));
			}
			
		}

		[HttpPost]
        public ViewResult Spisak(string kljucnarec, string opcija)
        {
			if (opcija == null)
				ModelState.AddModelError("", "Opcija nije odabrana");
			if (kljucnarec == null)
				ModelState.AddModelError("", "Nije uneta kljucna rec za pretragu");

			List<MasterTema> rezultat = repozitorijum.MasterTeme.Include(p => p.Mentor).Include(p => p.Student).
					Include(p => p.Komisija).ThenInclude(p => p.Nastavnik).OrderBy(p => p.DatumNNV).ToList();

            if (ModelState.IsValid)
			{
				if (opcija == "mentor")
					return View(rezultat.Where(p => p.Mentor.Ime == kljucnarec || p.Mentor.Prezime == kljucnarec)
					            .OrderBy(p => p.DatumNNV));
				else
					return View(rezultat.Where(p => p.Student.Ime == kljucnarec || p.Student.Prezime == kljucnarec)
					            .OrderBy(p => p.DatumNNV));
			}
			else
				return View(rezultat);
        }
	}
}

pismeni-ispiti/zadaci/januar2019_resenje/MasterTeme/Views/MasterTeme/Spisak.cshtml
@model IEnumerable<MasterTema>

<form class="form-inline" asp-action="Spisak" asp-controller="MasterTeme" method="POST">
  <div class="form-group">
    <select class="form-control" name="opcija">
		<option value=""> Izaberite opciju </option>
		<option value="mentor">Ime ili prezime mentora</option>
		<option value="student">Ime ili prezime studenta</option>
    </select>
    <input class="form-control" placeholder="kljucna rec" name="kljucnarec"  />
  	<button type="submit" class="btn btn-default">Pretraga</button>
  </div>
</form>

<div asp-validation-summary="All"></div>

<br><br><br><br>

@foreach (MasterTema p in Model){
 	   @Html.Partial("TemeIspis", p)
}